### ISSUE TITLE
C5_W4_QA_dataset: missing from datasets import load_from_disk

### ISSUE THREAD

**Issue by TaeheeJeong** [Ankit-Kumar-Saini/Coursera_Specializations#1]
In C5 - Sequence Models/Week4/Question Answering, QA_dataset.ipynb 
"from datasets import load_from_disk" error comes out since there is no datasets folder. 

Can you add datasets folder?

**Comment by Ankit-Kumar-Saini** [comment]
The dataset is present inside the data folder. The dataset is split into train and test sets.
