### ISSUE TITLE
C5_W4_Name Entity Recognition: missing files in model folder

### ISSUE THREAD

**Issue by TaeheeJeong** [Ankit-Kumar-Saini/Coursera_Specializations#2]
In C5 - Sequence Models/ Week4/ Named Entity Recognition, Transformer_application_Named_Entity_Recognition.ipynb

1.4 - Optimization
model = TFDistilBertForTokenClassification.from_pretrained('model/', num_labels=len(unique_tags))
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5'] found in directory model/ or `from_pt` set to False

Can you add pytorch_model.bin and tf_model.h5 in the model directory?

**Comment by Ankit-Kumar-Saini** [comment]
tf_model.h5 and pytorch_model.bin are very large files and hence I haven't uploaded them.
